import 'package:flutter/material.dart';

class AppModel {
  final String name, image, description, category;
  final double rating;
  final int review, price;
  List<Color> fcolor;
  List<String> size;
  bool isCheck;

  AppModel({
    required this.name,
    required this.image,
    required this.description,
    required this.category,
    required this.rating,
    required this.review,
    required this.price,
    required this.fcolor,
    required this.size,
    required this.isCheck,
  });
}

List<AppModel> fashionEcommerceApp = [
  AppModel(
    name: "Oversized Fit Printed Mesh T-Shirt",
    image: 'assets/shirts/image1.jpg',
    description: "A stylish oversized mesh t-shirt with breathable fabric.",
    category: "Women",
    rating: 4.9,
    review: 136,
    price: 295,
    fcolor: [Colors.black, Colors.blue, Colors.green],
    size: ["XS", "S", "M"],
    isCheck: true,
  ),
  AppModel(
    name: "Classic Cotton Polo Shirt",
    image: 'assets/shirts/image2.jpg',
    description: "A comfortable polo shirt with a soft cotton finish.",
    category: "Men",
    rating: 4.7,
    review: 112,
    price: 450,
    fcolor: [Colors.green, Colors.white, Colors.blue],
    size: ["S", "M", "L", "XL"],
    isCheck: false,
  ),
  AppModel(
    name: "Casual Striped T-Shirt",
    image: 'assets/shirts/image3.jpg',
    description: "A casual striped tee, perfect for everyday wear.",
    category: "Women",
    rating: 4.5,
    review: 98,
    price: 320,
    fcolor: [Colors.red, Colors.white, Colors.pink[100]!],
    size: ["M", "L", "XL"],
    isCheck: false,
  ),
  AppModel(
    name: "Kids' Graphic Print Tee",
    image: 'assets/shirts/image4.jpg',
    description: "A fun and vibrant graphic tee for kids.",
    category: "Child",
    rating: 4.8,
    review: 75,
    price: 250,
    fcolor: [Colors.yellow, Colors.orange, Colors.blue],
    size: ["2Y", "4Y", "6Y"],
    isCheck: false,
  ),
  AppModel(
    name: "Men's Sports Performance T-Shirt",
    image: 'assets/shirts/image5.jpg',
    description: "A moisture-wicking t-shirt for active performance.",
    category: "Men",
    rating: 4.6,
    review: 142,
    price: 520,
    fcolor: [Colors.black, Colors.grey, Colors.red],
    size: ["M", "L", "XL", "XXL"],
    isCheck: false,
  ),
  AppModel(
    name: "Sleeveless Tank Top",
    image: 'assets/shirts/image6.jpg',
    description: "A comfortable tank top for casual wear.",
    category: "Women",
    rating: 4.3,
    review: 67,
    price: 280,
    fcolor: [Colors.purple, Colors.black, Colors.green],
    size: ["S", "M", "L"],
    isCheck: false,
  ),
  AppModel(
    name: "Graphic Hoodie",
    image: 'assets/shirts/image7.jpg',
    description: "A stylish and cozy hoodie with printed graphics.",
    category: "Men",
    rating: 4.9,
    review: 210,
    price: 750,
    fcolor: [Colors.blue, Colors.grey, Colors.white],
    size: ["M", "L", "XL", "XXL"],
    isCheck: true,
  ),
  AppModel(
    name: "Full-Sleeve Thermal Shirt",
    image: 'assets/shirts/image8.jpg',
    description: "A warm and breathable thermal wear for winter.",
    category: "Men",
    rating: 4.8,
    review: 180,
    price: 650,
    fcolor: [Colors.black, Colors.blue, Colors.brown],
    size: ["S", "M", "L", "XL"],
    isCheck: true,
  ),
  AppModel(
    name: "Cartoon Print Baby Tee",
    image: 'assets/shirts/image9.jpg',
    description: "A cute cartoon printed tee for toddlers.",
    category: "Child",
    rating: 4.7,
    review: 95,
    price: 200,
    fcolor: [Colors.pink, Colors.lightBlue, Colors.yellow],
    size: ["1Y", "2Y", "3Y"],
    isCheck: true,
  ),
  AppModel(
    name: "Loose Fit Linen Shirt",
    image: 'assets/shirts/image10.jpg',
    description: "A breathable linen shirt for a casual summer look.",
    category: "Women",
    rating: 4.4,
    review: 130,
    price: 480,
    fcolor: [Colors.blue, Colors.red, Colors.lightGreen],
    size: ["M", "L", "XL"],
    isCheck: true,
  ),
  AppModel(
    name: "Boys' Checkered Shirt",
    image: 'assets/shirts/image11.jpg',
    description: "A stylish checkered button-up shirt for boys.",
    category: "Child",
    rating: 4.5,
    review: 89,
    price: 340,
    fcolor: [Colors.red, Colors.blue, Colors.green],
    size: ["3Y", "5Y", "7Y"],
    isCheck: true,
  ),
  AppModel(
    name: "Slim Fit Formal Shirt",
    image: 'assets/shirts/image12.jpg',
    description: "A modern slim fit shirt for office wear.",
    category: "Men",
    rating: 4.8,
    review: 175,
    price: 600,
    fcolor: [Colors.orange, Colors.blue, Colors.grey],
    size: ["S", "M", "L", "XL", "XXL"],
    isCheck: true,
  ),
  AppModel(
    name: "Women's Floral Blouse",
    image: 'assets/shirts/image13.jpg',
    description: "A soft floral printed blouse for a trendy look.",
    category: "Women",
    rating: 4.6,
    review: 120,
    price: 410,
    fcolor: [Colors.pink, Colors.blue, Colors.yellow],
    size: ["XS", "S", "M"],
    isCheck: true,
  ),
  AppModel(
    name: "Men's Denim Shirt",
    image: 'assets/shirts/image14.jpg',
    description: "A rugged denim shirt for casual outfits.",
    category: "Men",
    rating: 4.7,
    review: 155,
    price: 690,
    fcolor: [Colors.blue, Colors.black, Colors.grey],
    size: ["M", "L", "XL"],
    isCheck: true,
  ),
  AppModel(
    name: "Girls' Glitter Party Dress",
    image: 'assets/shirts/image15.jpg',
    description: "A sparkly dress for special occasions.",
    category: "Child",
    rating: 4.9,
    review: 135,
    price: 550,
    fcolor: [Colors.purple, Colors.blue, Colors.yellow],
    size: ["4Y", "6Y", "8Y"],
    isCheck: false,
  ),
  AppModel(
    name: "Comfortable Nightwear Set",
    image: 'assets/shirts/image16.jpg',
    description: "A cozy nightwear set for a good night’s sleep.",
    category: "Women",
    rating: 4.3,
    review: 95,
    price: 460,
    fcolor: [Colors.pink, Colors.blue, Colors.red],
    size: ["S", "M", "L"],
    isCheck: false,
  ),
  AppModel(
    name: "Men's Classic Suit Shirt",
    image: 'assets/shirts/image17.jpg',
    description: "A sleek formal shirt for business professionals.",
    category: "Men",
    rating: 4.8,
    review: 190,
    price: 720,
    fcolor: [Colors.orange, Colors.brown, Colors.black],
    size: ["S", "M", "L", "XL"],
    isCheck: false,
  ),
  AppModel(
    name: "Girls' Cotton Summer Dress",
    image: 'assets/shirts/image18.jpg',
    description: "A breathable and comfortable summer dress.",
    category: "Child",
    rating: 4.6,
    review: 110,
    price: 300,
    fcolor: [Colors.yellow, Colors.green, Colors.pink],
    size: ["3Y", "5Y", "7Y"],
    isCheck: true,
  ),
  AppModel(
    name: "Men's Checked Flannel Shirt",
    image: 'assets/shirts/image19.jpg',
    description: "A cozy flannel shirt perfect for fall and winter.",
    category: "Men",
    rating: 4.9,
    review: 200,
    price: 580,
    fcolor: [Colors.red, Colors.black, Colors.green],
    size: ["M", "L", "XL", "XXL"],
    isCheck: true,
  ),
  AppModel(
    name: "Women's Sleeveless Summer Dress",
    image: 'assets/shirts/image20.jpg',
    description: "A light and breezy sleeveless dress.",
    category: "Women",
    rating: 4.7,
    review: 140,
    price: 490,
    fcolor: [Colors.orange, Colors.red, Colors.pink],
    size: ["XS", "S", "M"],
    isCheck: false,
  ),
  AppModel(
    name: "Boys' Superhero Print T-Shirt",
    image: 'assets/shirts/image21.jpg',
    description: "A cool superhero-themed t-shirt for young boys.",
    category: "Child",
    rating: 4.8,
    review: 125,
    price: 270,
    fcolor: [Colors.blue, Colors.red, Colors.yellow],
    size: ["4Y", "6Y", "8Y", "10Y"],
    isCheck: true,
  ),
  //teens
  AppModel(
    name: "Trendy Denim Jacket",
    image: 'assets/shirts/teen1.png',
    description: "A stylish denim jacket perfect for casual wear.",
    category: "Teens",
    rating: 4.5,
    review: 98,
    price: 1200,
    fcolor: [Colors.blue, Colors.black, Colors.grey],
    size: ["S", "M", "L", "XL"],
    isCheck: false,
  ),
  AppModel(
    name: "Casual Hoodie",
    image: 'assets/shirts/teen2.png',
    description: "A warm and comfortable hoodie for everyday wear.",
    category: "Teens",
    rating: 4.6,
    review: 150,
    price: 950,
    fcolor: [Colors.red, Colors.white, Colors.black],
    size: ["S", "M", "L"],
    isCheck: false,
  ),
  AppModel(
    name: "Graphic T-Shirt",
    image: 'assets/shirts/teen3.webp',
    description: "A cool graphic tee with a modern design.",
    category: "Teens",
    rating: 4.3,
    review: 210,
    price: 600,
    fcolor: [Colors.black, Colors.yellow, Colors.blue],
    size: ["XS", "S", "M", "L"],
    isCheck: false,
  ),
  // for baby
  AppModel(
    name: "Soft Cotton Onesie",
    image: 'assets/shirts/baby1.png',
    description: "A soft and breathable cotton onesie for babies.",
    category: "Baby",
    rating: 4.9,
    review: 200,
    price: 450,
    fcolor: [Colors.white, Colors.pink, Colors.blue],
    size: ["0-3M", "3-6M", "6-9M", "9-12M"],
    isCheck: false,
  ),
  AppModel(
    name: "Warm Baby Sweater",
    image: 'assets/shirts/baby2.png',
    description: "A warm knitted sweater for little ones.",
    category: "Baby",
    rating: 4.8,
    review: 130,
    price: 700,
    fcolor: [Colors.lightBlue, Colors.yellow, Colors.purple],
    size: ["3M", "6M", "9M", "12M"],
    isCheck: false,
  ),
  AppModel(
    name: "Cute Animal Print Romper",
    image: 'assets/shirts/baby3.webp',
    description: "A cute romper with animal prints for babies.",
    category: "Baby",
    rating: 4.7,
    review: 175,
    price: 620,
    fcolor: [Colors.orange, Colors.green, Colors.brown],
    size: ["0-3M", "3-6M", "6-9M"],
    isCheck: false,
  ),
];
const myDescription1 = "Elevate you casual wardrobe with our";

const myDescription2 =
    "crafted from premiums comfort,this relaxed-fit tee feature";
